import { SQL } from "bun";

export const sql = process.env.DATABASE_URL === undefined ? new SQL() : new SQL(process.env.DATABASE_URL);

let databaseReady: Promise<void> | null = null;

export function ensureDatabase(): Promise<void> {
	databaseReady ??= migrate();
	return databaseReady;
}

async function migrate(): Promise<void> {
	await sql`
CREATE TABLE IF NOT EXISTS app_user (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	notion_user_id TEXT NOT NULL UNIQUE,
	notion_name TEXT NOT NULL,
	notion_avatar_url TEXT,
	notion_access_token TEXT NOT NULL,
	notion_refresh_token TEXT,
	notion_bot_id TEXT,
	notion_workspace_id TEXT,
	notion_workspace_name TEXT,
	notion_page_id TEXT,
	notion_groups_database_id TEXT,
	notion_groups_data_source_id TEXT,
	notion_links_database_id TEXT,
	notion_links_data_source_id TEXT,
	created_at INTEGER NOT NULL,
	updated_at INTEGER NOT NULL
)
`;

	await sql`
CREATE INDEX IF NOT EXISTS notion_user_id_index ON app_user(notion_user_id)
`;

	await sql`
CREATE TABLE IF NOT EXISTS session (
	id TEXT NOT NULL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
	expires_at INTEGER NOT NULL
)
`;
}
